# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name                   = "dx-playground"
    description            = "A playground for the DevEx team"
    topics                 = ["dx", "typescript", "playground"]
    reviewers_teams        = ["engineering-team-devex"]
    pull_request_bypassers = ["pagopa/engineering-team-devex"]
    environments           = ["dev"]
    has_issues             = true
  }
}
