# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name            = "dx-playground"
    description     = "A playground for the DevEx team"
    topics          = ["dx", "typescript"]
    reviewers_teams = ["engineering-team-devex"]
    environments    = ["dev"]
  }
}
