infra:
  - changed-files:
      - any-glob-to-any-file: ['infra/**']

workflows:
  - changed-files:
      - any-glob-to-any-file: [ '.github/workflows/**' ]

changeset:
  - changed-files:
      - any-glob-to-any-file: [ '.changeset/**' ]
