/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { TaskId } from "./TaskId";
import { TaskTitle } from "./TaskTitle";
import { TaskState } from "./TaskState";
import * as t from "io-ts";

// required attributes
const TaskItemR = t.interface({
  id: TaskId,

  title: TaskTitle,

  state: TaskState
});

// optional attributes
const TaskItemO = t.partial({});

export const TaskItem = t.intersection([TaskItemR, TaskItemO], "TaskItem");

export type TaskItem = t.TypeOf<typeof TaskItem>;
