packages:
  - apps/*
  - packages/*
  - infra/*

catalog:
  '@azure/cosmos': ^4.4.1
  '@azure/functions': ^4.7.2
  '@azure/identity': ^4.10.1
  '@cdktf/provider-azurerm': ^14.2.0
  '@pagopa/azure-tracing': ^0.4.10
  '@pagopa/eslint-config': ^5.0.0
  '@pagopa/handler-kit': ^1.1.0
  '@pagopa/handler-kit-azure-func': ^2.0.7
  '@pagopa/openapi-codegen-ts': ^14.0.0
  '@pagopa/ts-commons': ^13.1.2
  '@types/express': ^4.17.2
  '@types/js-yaml': ^4.0.9
  '@types/node': ^22.15.14
  '@vitest/coverage-v8': ^4.0.16
  azure-functions-core-tools: ^4.0.7317
  cdktf: ^0.21.0
  constructs: ^10.4.2
  esbuild: ^0.27.1
  eslint: ^9.39.1
  fp-ts: ^2.16.10
  io-ts: ^2.2.22
  js-yaml: ^4.1.0
  prettier: ^3.7.4
  shx: ^0.4.0
  swagger-cli: ^4.0.4
  ts2esm: ^2.2.7
  typescript: ^5.8.3
  ulid: ^3.0.2
  vitest: ^4.0.16
  vitest-mock-extended: ^3.1.0

catalogs:
  next:
    eslint-config-next: ^16.0.7
    next: ^16.1.1

configDependencies:
  pnpm-plugin-pagopa: 1.0.0+sha512-fWP4sdK5yH3OXi1oZeMEcMzBtjINfXx6woFOuzWtdlvuF7Co3vFJ3UIFLrOAolbYrXi4b3r2pIMESJt7vilizA==

onlyBuiltDependencies:
  - azure-functions-core-tools
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
