packages:
  - apps/*
  - packages/*
  - infra/*

catalog:
  typescript: ^5.8.3
  esbuild: ^0.25.4
  eslint: ^9.39.1
  prettier: ^3.6.2
  '@pagopa/eslint-config': ^5.0.0
  vitest: ^3.1.4
  vitest-mock-extended: ^3.1.0
  '@vitest/coverage-v8': ^3.1.4
  fp-ts: ^2.16.10
  io-ts: ^2.2.22
  '@azure/functions': ^4.7.2
  '@azure/identity': ^4.10.1
  '@azure/cosmos': ^4.4.1
  azure-functions-core-tools: ^4.0.7317
  '@pagopa/ts-commons': ^13.1.2
  '@pagopa/handler-kit': ^1.1.0
  '@pagopa/handler-kit-azure-func': ^2.0.7
  '@pagopa/azure-tracing': ^0.4.0
  '@pagopa/openapi-codegen-ts': ^14.0.0
  cdktf: ^0.21.0
  constructs: ^10.4.2
  '@cdktf/provider-azurerm': ^14.2.0
  shx: ^0.4.0
  js-yaml: ^4.1.0
  ulid: ^3.0.0
  '@types/node': ^22.15.14
  '@types/express': ^4.17.2
  '@types/js-yaml': ^4.0.9
  ts2esm: ^2.2.7
  swagger-cli: ^4.0.4

configDependencies:
  pnpm-plugin-pagopa: 1.0.0+sha512-fWP4sdK5yH3OXi1oZeMEcMzBtjINfXx6woFOuzWtdlvuF7Co3vFJ3UIFLrOAolbYrXi4b3r2pIMESJt7vilizA==
