name: 'Run and Redact Terraform Plan'
description: 'Execute `terraform plan` and redact sensitive information from the output.'

inputs:
  working-directory:
    description: 'The directory where terraform plan will be executed. (Defaults to the root of the repository)'
    required: false
    default: '.'

outputs:
  redacted_plan:
    description: "The redacted output of the `terraform plan` command."
  exit_code:
    description: "The exit code of the `terraform plan` command. 0 indicates success."

runs:
  using: "composite"
  steps:

    - name: (debug) show action path
      shell: bash
      run: |
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        ls -la "$GITHUB_ACTION_PATH"

    - name: (debug) show action path 2
      shell: bash
      run: |
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        ls -la "$GITHUB_ACTION_PATH"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run Terraform Plan and Redact Output
      id: plan
      shell: bash
      run: |
        REDACTED_OUTPUT=$(python3 $GITHUB_ACTION_PATH/scripts/run_plan.py)
        PLAN_EXIT_CODE=${PIPESTATUS[0]}

        echo "exit_code=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT

        EOF_MARKER=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16)
        echo "redacted_plan<<$EOF_MARKER" >> $GITHUB_OUTPUT
        echo "$REDACTED_OUTPUT" >> $GITHUB_OUTPUT
        echo "$EOF_MARKER" >> $GITHUB_OUTPUT
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
