name: 'Run and Redact Terraform Plan'
description: 'Execute `terraform plan` and redact sensitive information from the output.'

inputs:
  working-directory:
    description: 'The directory where terraform plan will be executed. (Defaults to the root of the repository)'
    required: false
    default: '.'

outputs:
  redacted_plan:
    description: "The redacted output of the `terraform plan` command."
  exit_code:
    description: "The exit code of the `terraform plan` command. 0 indicates success."

runs:
  using: "composite"
  steps:
    - name: Run Terraform Plan and Redact Output
      id: plan
      shell: bash
      run: |
        set -eo pipefail

        echo "--- Executing Plan in: $WORKING_DIRECTORY ---"
        cd $WORKING_DIRECTORY

        PLAN_FILE="redacted_plan.txt"
        python3 $GITHUB_ACTION_PATH/run_plan.py "$PLAN_FILE"
        PLAN_EXIT_CODE=$?

        echo "--- Plan executed with exit code: $PLAN_EXIT_CODE ---"

        REDACTED_OUTPUT=$(cat "$PLAN_FILE")
        echo "CAAAAAT FILE"
        cat "$PLAN_FILE"
        rm "$PLAN_FILE"

        # Set Outputs
        echo "exit_code=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT

        echo 'redacted_plan<<EOF' >> $GITHUB_OUTPUT
        echo $REDACTED_OUTPUT >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
