---
title: "Test Mermaid"
config:
  theme: mc
  fontFamily: Gill Sans, sans-serif;
---
graph LR
    subgraph PagoPA["PagoPA"]

        subgraph VNet["VNet (ItalyNorth)"]
            AppIO["`App IO`"]
            HubAppGwPEP["test-pep-01"]
            HubAppGwPrivateDNS["test.pagopa.it"]
        end
        subgraph FrontDoor["Global"]
          IOWebCDN["`IO Web
            (Static Website)`"]
        end
        AppGwPublicDNS["test.pagopa.it"]
        CDNDNS["test.io.pagopa.it"]
    end


    AppIO --> HubAppGwPEP --> HubAppGwPrivateDNS
    IOWebCDN --> AppGwPublicDNS

    ThirdParties --> CDNDNS --> ITWalletCDN

    ITWalletCDN@{ icon: "azure:front-door-and-cdn-profiles", pos: "b" }
    IOWebCDN@{ icon: "azure:front-door-and-cdn-profiles", pos: "b" }
    HubAppGwPEP@{ icon: "azure:private-endpoints", pos: "b" }
    HubAppGwPrivateDNS@{icon: "azure:dns-zones", pos: "b"}
    CDNDNS@{icon: "azure:dns-zones", pos: "b"}
    AppGwPublicDNS@{icon: "azure:dns-zones", pos: "b"}
    AppIO@{ icon: "azure:app-service-plans", pos: "b" }

    classDef macroBlock stroke-dasharray: 5 5, stroke-width:3px
    classDef subBlock stroke-dasharray: 5 5, stroke-width:2px
    classDef thirdPartiesClass fill:#e8f5e9,stroke:#2e7d32,stroke-width:1px
    classDef pagoPAStyle fill:#e8f4fd,stroke:#3498db,stroke-width:2px
    classDef psnStyle fill:#edf7f6,stroke:#16a085,stroke-width:2px
    classDef psnGlobalStyle fill:#fce4ec,stroke:#c2185b,stroke-width:2px
    classDef hubStyle fill:#fff4e6,stroke:#d68910,stroke-width:1px
    classDef spokeStyle fill:#f4ecf7,stroke:#8e44ad,stroke-width:1px
    classDef disabledStyle fill:#f5f5f5,stroke:#d3d3d3,stroke-width:1px,stroke-dasharray: 3 3,color:#999999,opacity:0.6

    class PagoPA pagoPAStyle
    class PSN psnStyle
    class PSNGlobal psnGlobalStyle
    class Hub,HubAppGwWaf hubStyle
    class Spoke spokeStyle
    class VNet,FrontDoor pagoPAStyle
    class ITWalletRG,VNetWallet,GHRunnerRG,WalletSA,WalletCDNSA spokeStyle

    class RelyingParty thirdPartiesClass
    class CredentialIssuer thirdPartiesClass
