name: Build and Push DevContainer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"

permissions:
  contents: read
  id-token: write
  attestations: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log in to the Container registry
        id: login-github
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PAT }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          push: filter
          refFilterForPush: refs/heads/main
          imageTag: ${{ steps.meta.outputs.tags }}
          platform: linux/amd64

      - name: Output image details
        run: |
          echo "Image pushed to: ${{ env.REGISTRY }}/${IMAGE_NAME}"
          echo "Tags: ${STEPS_META_OUTPUTS_TAGS}"
        env:
          STEPS_META_OUTPUTS_TAGS: ${{ steps.meta.outputs.tags }}
