name: Call Release Candidate Workflow
on:
  issue_comment:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call-release-candidate:
    name: Release Candidate
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/release-candidate') }}
    uses: ./.github/workflows/release_candidate_command.yaml@main
    with:
      pr_number: ${{ github.event.issue.number }}
    secrets:
      gh_bot_pat: ${{ secrets.GH_BOT_PAT }}
      npm_token: ${{ secrets.NPM_TOKEN }}
