name: Call Release Candidate Workflow
on:
  issue_comment:
    types: [created]

jobs:
  call_release_candidate:
    name: Release Candidate
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/release-candidate') }}
    uses: ./.github/workflows/release_candidate_command.yaml
    permissions:
      contents: write
      pull-requests: write
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    with:
      pr_number: ${{ github.event.issue.number }}
    secrets:
      gh_bot_pat: ${{ secrets.GH_BOT_PAT }}
      npm_token: ${{ secrets.NPM_TOKEN }}
