name: Validate

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - apps/**
      - packages/**
      - package.json
      - go.work
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - nx.json
      - .nx/version-plans/**
      - .github/workflows/code_review.yaml

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: pagopa/dx/.github/workflows/validate-v1.yaml@main
    secrets: inherit
    permissions:
      actions: read
      contents: read
      pull-requests: write
