name: Infra Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"
      - ".github/workflows/code_review_infra.yaml"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  code_review_dev:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@ci-det-phase/01
    name: Code Review Infra Plan
    secrets: inherit
    with:
      environment: dev
      override_github_environment: infra-dev
      base_path: infra/resources
      infra_cd_identity_name: dx-d-itn-playground-infra-github-cd-id-01
      infra_cd_identity_resource_group_name: dx-d-itn-playground-rg-01
