name: Infra Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      # Trigger the workflow when resources are modified
      - "infra/resources/**"
      # Trigger the workflow when the involved workflows are modified
      - ".github/workflows/code_review_infra.yaml"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  code_review_dev:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@ci-ai-phase/05
    name: Code Review Infra Plan
    secrets: inherit
    with:
      environment: dev
      override_github_environment: infra-dev
      base_path: infra/resources
      use_private_agent: true
      terraform_permission_check_enabled: true
      terraform_permission_check_gateway_url: https://dx-d-itn-ai-apim-01/ai/v1/responses
      terraform_permission_check_model_deployment_name: gpt-5-5
      terraform_permission_check_cd_identity_name: dx-d-itn-playground-infra-github-cd-id-01
      terraform_permission_check_azure_mcp_enabled: true
