name: Infra Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      # Trigger the workflow when resources are modified
      - "infra/resources/**"
      # Trigger the workflow when the involved workflows are modified
      - ".github/workflows/code_review_infra.yaml"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  code_review_dev:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@feat-add-application-insight-plan #main
    name: Code Review Infra Plan
    secrets: inherit
    with:
      environment: dev
      override_github_environment: infra-dev
      base_path: infra/resources
      connection_string: "InstrumentationKey=bd858043-3e63-4354-aa7f-73e273c68525;IngestionEndpoint=https://italynorth-0.in.applicationinsights.azure.com/;LiveEndpoint=https://italynorth.livediagnostics.monitor.azure.com/;ApplicationId=e2b4c152-d43c-47d1-ac0f-9870d8a79e98"
