name: Enrich PR

on:
  pull_request:

jobs:

  add_assignee:
    name: Add assignee
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: '.github/auto-assign.yaml'

  add_labels:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Label PR
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yaml'
          sync-labels: true

      - name: Add size label
        uses: pagopa/github-actions-template/check-pr-size@713f5abd8f8ee210e5f6a4243ae52eb7c1b3b5ab # v2.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignored_files: 'pnpm-lock.yaml, infra/**/.terraform.lock.hcl'
          min_size: 200
          max_size: 800
