name: Enrich PR

on:
  pull_request:

jobs:

  check_unsigned_commits:
    name: Check unsigned commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1771231294
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_PAT }}

      # Corepack is an official tool by Node.js that manages package managers versions
      - name: Setup yarn
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: yarn

      - name: Build GitHub helper
        run: yarn workspace github-helper build

      - name: Verify unsigned commits
        uses: ./.github/actions/unsigned_commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add_assignee:
    name: Add assignee
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          configuration-path: '.github/auto-assign.yaml'

  add_labels:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Label PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yaml'
          sync-labels: true

      - name: Add size label
        uses: pagopa/github-actions-template/check-pr-size@922ed4e43b0e45a5e47eb0296d550996d8c87c64 # v1.19.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignored_files: 'yarn.lock, infra/**/.terraform.lock.hcl .yarn/releases/*'
          min_size: 200
          max_size: 800
