name: Enrich PR

on:
  pull_request:

jobs:

  add_assignee:
    name: Add assignee
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: '.github/auto-assign.yaml'

  add_labels:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Label PR
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yaml'
          sync-labels: true

      - name: Add size label
        uses: pagopa/github-actions-template/check-pr-size@922ed4e43b0e45a5e47eb0296d550996d8c87c64 # v1.19.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignored_files: 'pnpm-lock.yaml, infra/**/.terraform.lock.hcl'
          min_size: 200
          max_size: 800
