name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Only on changes to ./changeset/*
      - .changeset/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1771231294
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_PAT }}

      - name: Node Setup
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git user
        run: |
          git config --global user.email "dx-pagopa-github-bot@pagopa.it"
          git config --global user.name "dx-pagopa-bot"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          version: pnpm run version
          publish: pnpm run release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
