name: Release Snapshot Version

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      gh_bot_pat:
        description: "GitHub Bot PAT for repository access."
        required: true
      npm_token:
        description: "npm token for package publishing."
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  snapshot_release:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1771231294
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_PAT }}

      - name: Setup Node
        uses: pagopa/dx/.github/actions/node-setup@main

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure Git user
        run: |
          git config --global user.email "dx-pagopa-github-bot@pagopa.it"
          git config --global user.name "dx-pagopa-bot"

      - name: Create Release Pull Request or Publish to npm (Snapshot)
        id: changesets
        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
        with:
          version: yarn dlx @changesets/cli version --snapshot rc
          publish: yarn dlx @changesets/cli publish --tag rc
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.gh_bot_pat }}
          NPM_TOKEN: ${{ secrets.npm_token }}
